### ISSUE TITLE
Detect when HTMLRenderer is appropriate

### ISSUE THREAD

**Issue by lrem** [tomchristie/flask-api#13]
After a glance on the web I expected Flask API to be a drop-in solution to add an API functionality to my app. However, it is necessary to add the `@set_renderers([HTMLRenderer])` before every view. Isn't it possible to make it implicit for functions returning an already rendered template?

**Comment by jacebrowning** [comment]
At a minimum, I don't think that JSONRenderer or BrowsableAPIRenderer should be used when the response content is a non-empty string (e.g. the return value of `render_template()`). I'm going to test a patch with that behavior to see if it breaks anything.

**Comment by jacebrowning** [comment]
This functionality is available in `Flask-API==0.7b2`.

**Comment by jacebrowning** [comment]
From my perspective, this issue can be closed. @lrem, please open a new issue if you run into a scenario where Flask API is not a drop-in solution.
