### ISSUE TITLE
BrowsableAPIRenderer does not escape angle brackets

### ISSUE THREAD

**Issue by tommorris** [tomchristie/flask-api#30]
If you have an Flask-API view that returns JSON containing angle brackets, like this...

     {"test": "I <3 Python"}

The angle bracket is not encoded as a <kbd>&amp;lt;</kbd> (or <kbd>&amp;gt;</kbd> in the case of a greater than angle bracket) entity in the HTML source code.

(I know from the README that the project isn't being maintained, but filing it for future reference. :smiley:)

**Comment by tomchristie** [comment]
Thanks tom
