### ISSUE TITLE
TypeError with query strings in Python 3

### ISSUE THREAD

**Issue by jacebrowning** [tomchristie/flask-api#31]
With `Flask-API==0.6.2`, visiting a URL with a query string causes a `TypeError`. Browsing `http://127.0.0.1:5000/api/?foo=bar` produces:

```
...

  File ".../env/lib/python3.4/site-packages/flask_api/request.py", line 171, in full_path
    return self.path + u'?' + self.query_string
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by tomchristie** [comment]
I'm not currently maintaining this project.

It's possible that I'll restart after the Django REST framework kickstarter project is complete, but otherwise it may be that it'd be better suited with someone else taking on a maintenance roll.

**Comment by jacebrowning** [comment]
It turns out this was fixed by https://github.com/tomchristie/flask-api/pull/14 and will be part of the next next release (`0.6.3`).
