### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by jacebrowning** [tomchristie/flask-api#33]
@tomchristie has mentioned in #31 and #32 that he is not currently maintaining this project. I'm interested in helping support a `0.6.x` release with bug fixes. Can we talk about which of these options is best to move forward on this repo:

1. contributors create pull requests and @tomchristie merges
2. add additional collaborators with push permission
3. transfer ownership of this repo to someone else
4. create a GitHub organization for this repo and add collaborators to that

**Comment by tomchristie** [comment]
Adding one or more additional collaborators with push permission, and a PyPI maintainer role sounds like a reasonable plan to me.

**Comment by tomchristie** [comment]
If someone demonstrates that they're willing and able to take on significant work on the project, then a proper GitHub organization might more be appropriate.

**Comment by tomchristie** [comment]
So (2) sounds sensible, with (4) a possibility at a later date. Reasonable?

**Comment by jacebrowning** [comment]
(2) sounds good to me. If you give me push permissions, the first thing I'll do is get the build passing again. Will you still want to review pull requests?

**Comment by tomchristie** [comment]
Thanks @jacebrowning! Added you now.

> Will you still want to review pull requests?

Not especially. I'll try to keep an eye on direction is all.

**Comment by jacebrowning** [comment]
Thanks! I plan to incorporate a Makefile from https://github.com/jacebrowning/template-python to automate all the development tasks.

**Comment by tomchristie** [comment]
@jacebrowning I prefer if that could be avoided :) - Makefiles aren't particular typical in most python projects.

Would be happy to talk that through tho, but best to tackle on a point by point basis (eg what specific tasks do you think need scripting?)

**Comment by jacebrowning** [comment]
@tomchristie  It would take care of things like virtualenv creation, package and tools installation, running tests and checks, and uploading packages. Do you have those steps laid out somewhere else?

**Comment by sloria** [comment]
After scanning the repo, here are some of the existing solutions to common dev tasks:

- Upload to pypi: `python setup.py publish`
- Run tests: `./runtests`
- Install dev requirements: `pip install -r requirements.txt`
- Build docs: `mkdocs build`
- Server docs: `mkdocs serve`

FWIW, I recommend [invoke](https://github.com/pyinvoke/invoke) as a task runner/build tool. It is similar to make but allows you to define tasks as Python functions.

**Comment by tomchristie** [comment]
I'm happy to see the above list added to the docs or readme.

I can't see that we otherwise another layer of tooling.

**Comment by auvipy** [comment]
You can add me as a collaborator too. I can review PR/create code changes through PR for review and keep the project improving to move forward.
