### ISSUE TITLE
Incompatibility with the Flask-CORS extension

### ISSUE THREAD

**Issue by benjaminsims** [tomchristie/flask-api#38]
I have been trying to combine Flask-API with the Flask-CORS extension in order to use it as the backend for a Single Page Application.

I've created a simple application to illustrate my backend here: https://gist.github.com/benjaminsims/6d51751b40e44eae1dcd

When I make a request to this server by doing:

    curl --include -X OPTIONS http://127.0.0.1:5000/   --header Access-Control-Request-Method:POST             --header Access-Control-Request-Headers:Content-Type  --header Origin:www.examplesite.com

I get the following error:

Error on request:
Traceback (most recent call last):
  File "/private/tmp/werkzeug/werkzeug/serving.py", line 181, in run_wsgi
    execute(self.server.app)
  File "/private/tmp/werkzeug/werkzeug/serving.py", line 171, in execute
    for data in application_iter:
  File "/private/tmp/werkzeug/werkzeug/wsgi.py", line 697, in __next__
    return self._next()
  File "/private/tmp/werkzeug/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
TypeError: 'NoneType' object is not iterable

If I add 'OPTIONS' to the list of methods supported by the route, this does not occur and things work normally as far as I can tell. However, this is not an option as it interferes with the authentication decorator (it causes OPTIONS requests to return 401 Unauthorized).

If I alter the code to use standard Flask rather then Flask-API (https://gist.github.com/benjaminsims/7f8dbe99d004ca446e53.js) then OPTIONS requests work normally.

I'm therefore wondering if this is an incompatibility between the two libraries that needs to be fixed, and more generally if there is a better way to get CORS working with Flask-API.

**Comment by jacebrowning** [comment]
@benjaminsims Can you reproduce this with the `0.6.3` release I did earlier today? This sound similar to https://github.com/tomchristie/flask-api/pull/27.

**Comment by benjaminsims** [comment]
That does the trick both in my example and real application. Thank you so much, I've been struggling with it for a while!
