### ISSUE TITLE
Excluding some routes?

### ISSUE THREAD

**Issue by Red5d** [tomchristie/flask-api#41]
Is it possible to exclude some routes from the web browsable API view? I wrote a web application with Flask that uses a few routes such as "/" to serve the web app page. Other routes like /api/<function> make up the underlying api that it uses.

Since this displays the API view when I go to the "/" route, my web app page is prevented from displaying, so I need a way to exclude those page view routes.

**Comment by jacebrowning** [comment]
This should be fixed in v0.7.
