### ISSUE TITLE
Make a 0.6.4 release into PyPi including markdown support

### ISSUE THREAD

**Issue by AdamSerafini** [tomchristie/flask-api#43]
It would be super cool to get a 0.6.4 release as it would be nice to have the markdown support that seems to have been added since 0.6.3.

Happy to help if I can? (but must confess, I don't know what the steps would be).

**Comment by jacebrowning** [comment]
Good idea! I'll get around to doing that in the next few days.

**Comment by jacebrowning** [comment]
@AdamSerafini you should be good to go!
