### ISSUE TITLE
Request.parser_classes and Request.renderer_classes are hardcoded to be default

### ISSUE THREAD

**Issue by bubenkoff** [tomchristie/flask-api#48]
This looks like a very strange hard-code of the request's configuration:

```python
    def preprocess_request(self):
        request.parser_classes = self.api_settings.DEFAULT_PARSERS
        request.renderer_classes = self.api_settings.DEFAULT_RENDERERS
        return super(FlaskAPI, self).preprocess_request()
```

so it makes it impossible to extend the Request class and set it's classes attributes to a different from default values

**Comment by tomchristie** [comment]
Why would you need to extend the request class to do so if you can set them in the api settings?

**Comment by bubenkoff** [comment]
makes sense...
let me try

**Comment by bubenkoff** [comment]
do you have an example of that approach?
i don't see a way to override those settings, actually

**Comment by bubenkoff** [comment]
ah right, found it

**Comment by tomchristie** [comment]
:+1:

**Comment by bubenkoff** [comment]
thanks!
