### ISSUE TITLE
pypi package for 0.6.6 contains .pyc files.

### ISSUE THREAD

**Issue by james-fanduel** [tomchristie/flask-api#55]
I am getting `ValueError: bad marshal data (unknown type code)` during install of an application with a requirement on 0.6.6. 

This looks like it could be due to the pypi package containing .pyc files.

**Comment by phobologic** [comment]
This seems like it's been happening since 0.6.3?  Is there a fix already in the source for this?  Any idea on a release date?

**Comment by jacebrowning** [comment]
The command that created the last three releases was `$ python setup.py publish` which calls:

https://github.com/tomchristie/flask-api/blob/799d8f50410375e91f993de10217615a6171ecea/setup.py#L58-L64

Do you see any issues that that setup code?

**Comment by jacebrowning** [comment]
I just reuploaded. Does `$ pip install flask-api==0.6.6.post1` work?

**Comment by phobologic** [comment]
That seems to have fixed it - thanks @jacebrowning !

**Comment by jacebrowning** [comment]
Cool! I think this might help in future: https://github.com/tomchristie/flask-api/commit/6c8720348fed5c04a347973d4a06e7bc24269f19#diff-2eeaed663bd0d25b7e608891384b7298R59

My guess is the `.pyc` files were hanging around when switching between different versions of Python.
