### ISSUE TITLE
Incompatibility with flask .11 error handling: TypeError: 'type' object is not iterable

### ISSUE THREAD

**Issue by vitriol** [tomchristie/flask-api#58]
Flask 0.11 Changed the order in which errorhandlers are executed and they added the type of the error handler in there making any app that registers flask-api to throw an error before being able to execute the proper error handler (app.py line 91)

What seems to work for me is to add the following in app.py:91

```
for typecheck, handler in chain(blueprint_handlers.items(), app_handlers.items()): 
```

since blueprint_handlers and app_handlers are now both `dict` objects

**Comment by jacebrowning** [comment]
A pull request including a test for this fix would be greatly appreciated!

**Comment by vitriol** [comment]
I would appreciate that too! I have never done that before and sadly I don't have time anytime soon to try it

**Comment by jacebrowning** [comment]
`Flask-API ~= 0.6.7` should work.
