### ISSUE TITLE
v0.7.0 release breaks expected behavior

### ISSUE THREAD

**Issue by skaven81** [tomchristie/flask-api#77]
One of the chief reasons we use FlaskAPI at Qualcomm is because of how easy it makes returning JSON content from a simple function.  However, it seems something between v0.6.9 and v0.7.0 broke this behavior; if you try to return data that isn't a `dict` or `list` from a Flask handler, you get a `text/html` response back, whereas you used to get an `application/json` response back.

In v0.6.9:
```
[pkrizak@balthasar]$ curl --include --insecure https://10.52.252.96:3519/api/v1/mapping/test_mapping/key1
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 8
Access-Control-Allow-Origin: *
Server: Werkzeug/0.12.1 Python/3.5.3
Date: Tue, 11 Apr 2017 03:40:13 GMT
Connection: keep-alive

"value1"
```

In v0.7.0:
```
[pkrizak@balthasar]$ curl --include --insecure https://10.52.252.96:3519/api/v1/mapping/test_mapping/key1
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 6
Access-Control-Allow-Origin: *
Server: Werkzeug/0.12.1 Python/3.5.3
Date: Tue, 11 Apr 2017 03:45:21 GMT
Connection: keep-alive

value1
```

It's OK if the new behavior is intentional -- if so, just please provide a way to get the old behavior back, because we are depending on it.

**Comment by jacebrowning** [comment]
This behavior is intentional.

One of the goals with the v0.7.0 release was to allow Flask-API to be a drop-in replacement for Flask (https://github.com/tomchristie/flask-api/issues/13). In order for this to work, Flask-API needs to ignore views that return HTML (text) from `render_template()` and other utilities.

In my opinion, a web API should return a hash, an array of hashes, or a mixture of both in order to be consumable by clients. That is, instead of `return "foobar"`, `return {"value": "foobar"}`.

**Comment by skaven81** [comment]
> In my opinion, a web API should return a hash, an array of hashes, or a mixture of both in order to be consumable by clients.

Well, it depends on how forgiving you are with what is considered "proper JSON".  http://www.json.org/ does not specify that a JSON document must be a list or an object at the top level, to be valid.  Our API happens to allow for drill-down access into larger data structures, ultimately terminating at a discrete value at a leaf somewhere.  So for example:

  GET /api/v1/some_resource/
  {
    "foo": {
        "bar": [
            "baz",
            "frozzle"
        ]
    }
  }

  GET /api/v1/some_resource/foo
  {
      "bar": [
          "baz",
          "frozzle"
      ]
  }

  GET /api/v1/some_resource/foo/bar
  [
        "baz",
        "frozzle"
    ]

  GET /api/v1/some_resource/foo/bar/1
   "frozzle"

**Comment by jacebrowning** [comment]
> please provide a way to get the old behavior back

We could add an `automatic_types` setting on `FlaskAPI` instances that defaults to `(list, dict)` but could be customized for your use case:

```
app = FlaskAPI(__name__)
app.automatic_types = (list, dict, str)
```

Would that work?

**Comment by skaven81** [comment]
I think this is a very elegant solution.  Perhaps the name `api_return_types` would be better?

**Comment by skaven81** [comment]
:+1: works great!
